### ISSUE TITLE
Client code appears to be saving string "none" here and the linked "if" condition treats as truthy

### ISSUE THREAD

**Issue by bZichett** [easydiffusion/sdkit#60]
https://github.com/easydiffusion/sdkit/blob/c1690edbbd78bafebcfeb4dd7d441f215ca6ba8b/sdkit/generate/image_generator.py#L452C8-L452C14

Not sure of impact, but will be clear to code authors.  Leaning towards no impact but maybe it matters for some reason unclear to me. 

I only noticed this when reading the logs after using seamless tiling but then changing it back to "none" and realized immediately what had occurred.

Could patch it here but I think a change on client to clear string or undefined rather than saving the string "none" or if "none" is used elsewhere in client code, perhaps a server side parser to cast "none" into empty value.  The question about this happening elsewhere in the client / server code is worth a cross repo code search for "none", perhaps?

**Comment by cmdr2** [comment]
Hi, the client code was fixed to use `None` instead of `"none"` when disabling tiling. Probably around the same time as your post :) https://github.com/easydiffusion/easydiffusion/commit/16f0950ebd018e4bc92ff496e69ee4f31bd448fb

From sdkit's perspective, the contract is to use `None` or `False` if tiling needs to be disabled. The previous sdkit implementation used `"none"` as the default value, which was a mistake.
